export const data = [
    { id: 1, title: "React Basics", category: "React" },
    { id: 2, title: "Advanced JavaScript", category: "JavaScript" },
    { id: 3, title: "CSS Animations", category: "CSS" },
    { id: 4, title: "Node.js for Beginners", category: "JavaScript" },
    { id: 5, title: "Introduction to Machine Learning", category: "AI/ML" },
    { id: 6, title: "Quantum Mechanics Overview", category: "Science" },
    { id: 7, title: "Climate Change and Its Effects", category: "Environment" },
    { id: 8, title: "Genetic Algorithms in Computer Science", category: "AI/ML" },
    { id: 9, title: "Web Performance Optimization", category: "Web Development" },
    { id: 10, title: "Deep Learning Techniques", category: "AI/ML" },
    { id: 11, title: "Astronomy Basics", category: "Science" },
    { id: 12, title: "The Future of Space Exploration", category: "Science" },
    { id: 13, title: "Machine Learning in Healthcare", category: "AI/ML" },
    { id: 14, title: "Biotechnology Advances", category: "Science" },
    { id: 15, title: "Energy Conservation Techniques", category: "Environment" },
    { id: 16, title: "Building RESTful APIs with Node.js", category: "Web Development" },
    { id: 17, title: "Understanding Deep Neural Networks", category: "AI/ML" },
    { id: 18, title: "The Science of Climate Modeling", category: "Science" },
    { id: 19, title: "Introduction to Cybersecurity", category: "Computer Science" },
    { id: 20, title: "The Impact of Artificial Intelligence on Society", category: "AI/ML" },
    { id: 21, title: "Data Science and Big Data Analytics", category: "Data Science" },
    { id: 22, title: "The Role of Data Science in Finance", category: "Data Science" },
    { id: 23, title: "Neural Networks and Machine Learning", category: "AI/ML" },
    { id: 24, title: "Ethics in AI and Machine Learning", category: "AI/ML" },
    { id: 25, title: "Geophysics and Seismology", category: "Science" },
    { id: 26, title: "Nanotechnology Applications", category: "Science" },
    { id: 27, title: "The Evolution of Web Development", category: "Web Development" },
    { id: 28, title: "Smart Grid Technology", category: "Environment" },
    { id: 29, title: "Understanding Blockchain Technology", category: "Computer Science" },
    { id: 30, title: "Astronomy and Space Observation", category: "Science" }
  ];
  